Vet Clinic Database
AbuTalha3/vet-clinic-database pull request #1
Opened 2023-10-24 21:49 UTC by AbuTalha3

**In this PR I have**
- Created a database named vet_clinic.
- Created a table named animals with the following columns:
    id: integer
    name: string
   date_of_birth: date
   escape_attempts: integer
   neutered: boolean
   weight_kg: decimal
- Added given data to the table.
- Wrote queries as required.

- Screen Shots
- 1. Create DATABASE and TABLE animals
![image](https://github.com/AbuTalha3/vet-clinic-database/assets/127955219/6b857f2f-7fa0-4e50-b31b-8432f39883d2)

- 2. Inserting DATA to Table
- 
![image](https://github.com/AbuTalha3/vet-clinic-database/assets/127955219/cb319401-d58e-4b1e-8553-8ca0278b9e5a)

-3. Queries Ran to find DATA
-
![image](https://github.com/AbuTalha3/vet-clinic-database/assets/127955219/4f0987da-8e9f-4b76-ba4b-30ca48d8210f)

-
![image](https://github.com/AbuTalha3/vet-clinic-database/assets/127955219/5f612aa4-4a54-4dbf-ab5f-826f392b8ef4)
-
![image](https://github.com/AbuTalha3/vet-clinic-database/assets/127955219/44aec49b-1849-4402-b0ff-82c4d6ada7bf)

2023-10-24 22:48 UTC, skyv26 requested changes
## Hi @AbuTalha3, 

Good job so far 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYjBkZWI1YTgxNDg4Y2QzMWU2MjkyNjQ2MmY1MmIzMjM4ZmI1MGU1OCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/fDWHJAmgrCeIw/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 

## Required Changes ♻️
- [ ] Please `adhere` to the project requirements 🙏🏻 , as I noticed that your `schema.sql` file `table` creation query not working at all and got an error related to syntax error for `ID` column. Kindly fix the syntax error and you can also take a look at the hint given below.

#### Problem
![image](https://github.com/AbuTalha3/vet-clinic-database/assets/66476329/d29833b6-c76f-4109-b041-babf37bf037d)

#### Hint
![image](https://github.com/AbuTalha3/vet-clinic-database/assets/66476329/b2ec6cbf-db4e-41ba-bd3a-85de99daca38)

- [ ] As I mentioned you should follow the `requirements` strictly because your file `data.sql` doesn't `reflect` in the changes, that is why I am writing my comment here regarding the missing data provided by **Microverse** in the form of instructions. Don't forget to change the screenshot after making the changes to the PR description.

#### Expected Data
![image](https://github.com/AbuTalha3/vet-clinic-database/assets/66476329/08b77cd5-f7b2-4049-a4e0-ea3c3fd19679)

- [ ] It seems like you added the `README` file using the `Microverse` template but your `README` file needs some updates or improved formatting. Your README file is not customized properly, some of the sections are redundant in your README file so please avoid the redundancy and customise your `README` file according to the `project` theme and also delete the `unnecessary` technology from your tech stack section. Implementing this changes will make your `README` file professional. Make sure also you don't have any broken link.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-24 22:48 UTC, skyv26 commented on queries.sql
- [ ] Please avoid adding queries which is not part of this milestone, and also either remove the output from this file OR `make` them comment as per `sql` syntax. Because, your table creation query is not working, and you haven't added the expected data correctly, that's why I would like to suggest you to re-read the requirements and do work accordingly. 

### Expectation
![image](https://github.com/AbuTalha3/vet-clinic-database/assets/66476329/78612fb7-4458-4b56-bc9a-4ffc7a425fef)

2023-10-25 15:53 UTC, shahadat3669 requested changes
Hi @AbuTalha3, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights

✅ Descriptive PR Description



 ## Required Changes ♻️

👏 Great work on updating the PR description with screenshots of your queries as added after the comment of the previous reviewer! However, a couple of points to consider:

- [ ] Kindly make sure to thoroughly review all the requested changes in the comments and update your code accordingly. It's essential to read and address each comment carefully to align your project with the given feedback.

- [ ] Second, I noticed that you added a comment after the review request. However, the comment does not seem to address any specific request that the previous reviewer had mentioned. To streamline the workflow, it is generally recommended to make necessary changes before requesting a review. Please keep in mind this point for future reference.



_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-25 17:47 UTC, divinecharlotte approved these changes
# Hello @AbuTalha3  😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 
### To Highlight 💯

- Good implementation of the required changes✔️
- Descriptive pr✔️






## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-25 17:49 UTC, merged